// Author: Zeno Ren
// Generated by Scripts/import-copilot-prices.py from the reviewed GitHub Docs page.
// Pricing data: https://docs.github.com/en/copilot/reference/copilot-billing/models-and-pricing
import Foundation

public enum CopilotPublicPricing {
    public static let sourceURL = "https://docs.github.com/en/copilot/reference/copilot-billing/models-and-pricing"
    public static let asOf = "2026-09-09"
    public static let models: [PublicModelPrice] = [
        .init(id: "gpt-5-mini", displayName: "GPT-5 mini", provider: "OpenAI", standard: .init(input: 0.25, cacheRead: 0.025, cacheWrite: nil, output: 2.0), contextThreshold: nil, longContext: nil, promotionThrough: nil),
        .init(id: "gpt-5.3-codex", displayName: "GPT-5.3-Codex", provider: "OpenAI", standard: .init(input: 1.75, cacheRead: 0.175, cacheWrite: nil, output: 14.0), contextThreshold: nil, longContext: nil, promotionThrough: nil),
        .init(id: "gpt-5.4", displayName: "GPT-5.4", provider: "OpenAI", standard: .init(input: 2.5, cacheRead: 0.25, cacheWrite: nil, output: 15.0), contextThreshold: 272000, longContext: .init(input: 5.0, cacheRead: 0.5, cacheWrite: nil, output: 22.5), promotionThrough: nil),
        .init(id: "gpt-5.4-mini", displayName: "GPT-5.4 mini", provider: "OpenAI", standard: .init(input: 0.75, cacheRead: 0.075, cacheWrite: nil, output: 4.5), contextThreshold: nil, longContext: nil, promotionThrough: nil),
        .init(id: "gpt-5.4-nano", displayName: "GPT-5.4 nano", provider: "OpenAI", standard: .init(input: 0.2, cacheRead: 0.02, cacheWrite: nil, output: 1.25), contextThreshold: nil, longContext: nil, promotionThrough: nil),
        .init(id: "gpt-5.5", displayName: "GPT-5.5", provider: "OpenAI", standard: .init(input: 5.0, cacheRead: 0.5, cacheWrite: nil, output: 30.0), contextThreshold: 272000, longContext: .init(input: 10.0, cacheRead: 1.0, cacheWrite: nil, output: 45.0), promotionThrough: nil),
        .init(id: "gpt-5.6-luna", displayName: "GPT-5.6 Luna", provider: "OpenAI", standard: .init(input: 0.2, cacheRead: 0.02, cacheWrite: 0.25, output: 1.2), contextThreshold: 200000, longContext: .init(input: 0.4, cacheRead: 0.04, cacheWrite: 0.5, output: 1.8), promotionThrough: nil),
        .init(id: "gpt-5.6-sol", displayName: "GPT-5.6 Sol", provider: "OpenAI", standard: .init(input: 4.0, cacheRead: 0.4, cacheWrite: 5.0, output: 20.0), contextThreshold: 272000, longContext: .init(input: 8.0, cacheRead: 0.8, cacheWrite: 10.0, output: 30.0), promotionThrough: nil),
        .init(id: "gpt-5.6-terra", displayName: "GPT-5.6 Terra", provider: "OpenAI", standard: .init(input: 2.0, cacheRead: 0.2, cacheWrite: 2.5, output: 12.0), contextThreshold: 272000, longContext: .init(input: 4.0, cacheRead: 0.4, cacheWrite: 5.0, output: 18.0), promotionThrough: nil),
        .init(id: "gpt-6-astra", displayName: "GPT-6 Astra", provider: "OpenAI", standard: .init(input: 10.0, cacheRead: 1.0, cacheWrite: 12.5, output: 50.0), contextThreshold: 272000, longContext: .init(input: 20.0, cacheRead: 2.0, cacheWrite: 25.0, output: 75.0), promotionThrough: nil),
        .init(id: "claude-haiku-4.5", displayName: "Claude Haiku 4.5", provider: "Anthropic", standard: .init(input: 1.0, cacheRead: 0.1, cacheWrite: 1.25, output: 5.0), contextThreshold: nil, longContext: nil, promotionThrough: nil),
        .init(id: "claude-sonnet-4", displayName: "Claude Sonnet 4", provider: "Anthropic", standard: .init(input: 3.0, cacheRead: 0.3, cacheWrite: 3.75, output: 15.0), contextThreshold: nil, longContext: nil, promotionThrough: nil),
        .init(id: "claude-sonnet-4.6", displayName: "Claude Sonnet 4.6", provider: "Anthropic", standard: .init(input: 3.0, cacheRead: 0.3, cacheWrite: 3.75, output: 15.0), contextThreshold: nil, longContext: nil, promotionThrough: nil),
        .init(id: "claude-opus-4.7", displayName: "Claude Opus 4.7", provider: "Anthropic", standard: .init(input: 5.0, cacheRead: 0.5, cacheWrite: 6.25, output: 25.0), contextThreshold: nil, longContext: nil, promotionThrough: nil),
        .init(id: "claude-opus-4.8", displayName: "Claude Opus 4.8", provider: "Anthropic", standard: .init(input: 5.0, cacheRead: 0.5, cacheWrite: 6.25, output: 25.0), contextThreshold: nil, longContext: nil, promotionThrough: nil),
        .init(id: "claude-opus-5", displayName: "Claude Opus 5", provider: "Anthropic", standard: .init(input: 5.0, cacheRead: 0.5, cacheWrite: 6.25, output: 25.0), contextThreshold: nil, longContext: nil, promotionThrough: nil),
        .init(id: "claude-sonnet-5", displayName: "Claude Sonnet 5", provider: "Anthropic", standard: .init(input: 2.0, cacheRead: 0.2, cacheWrite: 2.5, output: 10.0), contextThreshold: nil, longContext: nil, promotionThrough: nil),
        .init(id: "claude-opus-4.8-fast", displayName: "Claude Opus 4.8 (fast mode) (preview)", provider: "Anthropic", standard: .init(input: 10.0, cacheRead: 1.0, cacheWrite: 12.5, output: 50.0), contextThreshold: nil, longContext: nil, promotionThrough: nil),
        .init(id: "claude-fable-5", displayName: "Claude Fable 5", provider: "Anthropic", standard: .init(input: 10.0, cacheRead: 1.0, cacheWrite: 12.5, output: 50.0), contextThreshold: nil, longContext: nil, promotionThrough: nil),
        .init(id: "claude-fable-5.1", displayName: "Claude Fable 5.1", provider: "Anthropic", standard: .init(input: 10.0, cacheRead: 0.25, cacheWrite: 12.5, output: 50.0), contextThreshold: nil, longContext: nil, promotionThrough: nil),
        .init(id: "gemini-3.5-flash", displayName: "Gemini 3.5 Flash", provider: "Google", standard: .init(input: 1.5, cacheRead: 0.15, cacheWrite: nil, output: 9.0), contextThreshold: nil, longContext: nil, promotionThrough: nil),
        .init(id: "gemini-3.6-flash", displayName: "Gemini 3.6 Flash", provider: "Google", standard: .init(input: 0.75, cacheRead: 0.075, cacheWrite: nil, output: 3.75), contextThreshold: nil, longContext: nil, promotionThrough: "2026-12-31"),
        .init(id: "gemini-3.7-flash", displayName: "Gemini 3.7 Flash", provider: "Google", standard: .init(input: 0.75, cacheRead: 0.075, cacheWrite: nil, output: 3.75), contextThreshold: nil, longContext: nil, promotionThrough: "2026-12-31"),
        .init(id: "gemini-3.8-flash", displayName: "Gemini 3.8 Flash", provider: "Google", standard: .init(input: 0.75, cacheRead: 0.075, cacheWrite: nil, output: 3.75), contextThreshold: nil, longContext: nil, promotionThrough: "2026-12-31"),
        .init(id: "mai-code-1-flash", displayName: "MAI-Code-1-Flash", provider: "Microsoft", standard: .init(input: 0.75, cacheRead: 0.075, cacheWrite: nil, output: 4.5), contextThreshold: nil, longContext: nil, promotionThrough: nil),
        .init(id: "mai-code-1.1-flash", displayName: "MAI-Code-1.1-Flash", provider: "Microsoft", standard: .init(input: 0.2, cacheRead: 0.02, cacheWrite: nil, output: 1.2), contextThreshold: nil, longContext: nil, promotionThrough: nil),
        .init(id: "grok-4.5", displayName: "Grok 4.5", provider: "xAI", standard: .init(input: 2.0, cacheRead: 0.5, cacheWrite: nil, output: 6.0), contextThreshold: 200000, longContext: .init(input: 4.0, cacheRead: 1.0, cacheWrite: nil, output: 12.0), promotionThrough: nil),
        .init(id: "grok-4.6", displayName: "Grok 4.6", provider: "xAI", standard: .init(input: 2.0, cacheRead: 0.5, cacheWrite: nil, output: 6.0), contextThreshold: 200000, longContext: .init(input: 4.0, cacheRead: 1.0, cacheWrite: nil, output: 12.0), promotionThrough: nil),
        .init(id: "kimi-k2.7-code", displayName: "Kimi K2.7 Code", provider: "Moonshot AI", standard: .init(input: 0.95, cacheRead: 0.19, cacheWrite: nil, output: 4.0), contextThreshold: nil, longContext: nil, promotionThrough: nil),
        .init(id: "kimi-k3", displayName: "Kimi K3", provider: "Moonshot AI", standard: .init(input: 3.0, cacheRead: 0.3, cacheWrite: nil, output: 15.0), contextThreshold: nil, longContext: nil, promotionThrough: nil),
    ]
}
