#!/usr/bin/env python3
"""Transcribe the reviewed GitHub Docs pricing HTML into a reproducible catalog.
Author: Zeno Ren
Usage: python3 Scripts/import-copilot-prices.py HTML_PATH YYYY-MM-DD
"""
from html.parser import HTMLParser
from pathlib import Path
import sys, re, json, hashlib

class Tables(HTMLParser):
    def __init__(self):
        super().__init__(); self.tables=[]; self.rows=None; self.row=None; self.cell=None; self.sup=0; self.heading=None; self.provider=''
    def handle_starttag(self,t,a):
        if t in ['h2','h3']: self.heading=[]
        if t=='table': self.rows=[]
        if t=='tr' and self.rows is not None: self.row=[]
        if t in ['th','td'] and self.row is not None: self.cell=[]
        if t=='sup': self.sup+=1
    def handle_endtag(self,t):
        if t in ['h2','h3'] and self.heading is not None:
            self.provider=''.join(self.heading).strip(); self.heading=None
        if t in ['th','td'] and self.cell is not None:
            self.row.append(''.join(self.cell).strip()); self.cell=None
        if t=='tr' and self.row is not None: self.rows.append(self.row); self.row=None
        if t=='table' and self.rows is not None: self.tables.append((self.provider,self.rows)); self.rows=None
        if t=='sup': self.sup=max(0,self.sup-1)
    def handle_data(self,d):
        if self.heading is not None: self.heading.append(d)
        if self.cell is not None and not self.sup:self.cell.append(d)

root=Path(__file__).resolve().parent.parent
path=Path(sys.argv[1]); as_of=sys.argv[2]
assert re.fullmatch(r'\d{4}-\d{2}-\d{2}',as_of)
p=Tables();p.feed(path.read_text())
models={}; count=0

def rate(text):
    if text in ['Not applicable','N/A','—','']:return None
    assert re.fullmatch(r'\$[0-9,.]+',text),text
    return float(text.replace('$','').replace(',',''))

for provider,rows in p.tables:
    if not rows or not {'Model','Input','Output'}.issubset(rows[0]):continue
    for row in rows[1:]:
        assert len(row)==len(rows[0]),row
        d=dict(zip(rows[0],row)); name=d['Model']; ident=name.lower().replace(' (fast mode) (preview)','-fast').replace(' ','-')
        point={k:rate(d.get(col,'')) for k,col in [('input','Input'),('cacheRead','Cached input'),('cacheWrite','Cache write'),('output','Output')]}
        assert point['input'] is not None and point['output'] is not None and point['cacheRead'] is not None
        m=models.setdefault(ident,{'id':ident,'displayName':name,'provider':provider})
        tier=d.get('Tier','Default'); assert tier in ['Default','Long context']
        m['longContext' if tier=='Long context' else 'standard']=point
        threshold=d.get('Threshold (input tokens)','')
        if threshold and threshold!='Not applicable':
            n=re.search(r'(\d+)K',threshold);assert n,threshold;m['contextThreshold']=int(n[1])*1000
        if ident in ['gemini-3.6-flash','gemini-3.7-flash','gemini-3.8-flash']:m['promotionThrough']='2026-12-31'
        count+=1
assert count>=30 and len(models)>=25
for m in models.values():assert 'standard'in m and (('longContext'in m)==('contextThreshold'in m))
result={'author':'Zeno Ren','sourceURL':'https://docs.github.com/en/copilot/reference/copilot-billing/models-and-pricing','asOf':as_of,'currency':'USD','unit':'per 1 million tokens','basis':'Current reference prices applied across tools and historical usage; not historical invoices.','htmlSHA256':hashlib.sha256(path.read_bytes()).hexdigest(),'priceRows':count,'models':list(models.values())}
(root/'docs'/f'COPILOT_PRICES_{as_of}.json').write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n')

def lit(s):return json.dumps(s,ensure_ascii=False)
def point(p):return '.init(input: '+str(p['input'])+', cacheRead: '+str(p['cacheRead'])+', cacheWrite: '+('nil' if p['cacheWrite'] is None else str(p['cacheWrite']))+', output: '+str(p['output'])+')'
lines=['// Author: Zeno Ren','// Generated by Scripts/import-copilot-prices.py from the reviewed GitHub Docs page.','// Pricing data: '+result['sourceURL'],'import Foundation','','public enum CopilotPublicPricing {','    public static let sourceURL = '+lit(result['sourceURL']),'    public static let asOf = '+lit(as_of),'    public static let models: [PublicModelPrice] = [']
for m in models.values():
    lines.append('        .init(id: '+lit(m['id'])+', displayName: '+lit(m['displayName'])+', provider: '+lit(m['provider'])+', standard: '+point(m['standard'])+', contextThreshold: '+str(m.get('contextThreshold','nil'))+', longContext: '+(point(m['longContext']) if 'longContext'in m else 'nil')+', promotionThrough: '+(lit(m['promotionThrough']) if 'promotionThrough'in m else 'nil')+'),')
lines+=['    ]','}']
(root/'Sources/UsageCore/Pricing/CopilotPublicPricing.swift').write_text('\n'.join(lines)+'\n')
print(f'Imported {count} published price rows / {len(models)} models; as of {as_of}. Author: Zeno Ren')
